# name: My First Workflow

# on: push

# jobs:
#   hello:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Run a script
#         run: echo "Hello from GitHub Actions!"

name: Build and Share Artifact

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create demo build file
        run: |
          echo "This is my JAR file content" > app.jar
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: app.jar

  test:
    runs-on: ubuntu-latest
    needs: build   # Job 2 waits for Job 1
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Display file content
        run: cat app.jar
